#ifndef HALO_MESSAGE_TYPES_H
#define HALO_MESSAGE_TYPES_H

enum HaloMsgTypes
{
    ALL_DATA,
    ALL_DATA_DYNAMIC,
    VITALS,
    LOCATION,
    BATTERY,
    DEBUG,
    CRITICAL_ALERT,
    RESOLVED_EVENT
};

#endif //HALO_MESSAGE_TYPES_H
